name: Build & Publish PDF to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      # - name: Install Git
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y git
      - name: Build PDF
        uses: xu-cheng/latex-action@v4
        with:
          root_file: CV.tex
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          keep_files: false
          enable_jekyll: false